SELECT
  *
FROM
  "CASESTUDY"."BRIGHT"."COFFEE_SHOP"
LIMIT
10;
  ---------------------------------------
---I want to check my categorical columns
SELECT DISTINCT STORE_LOCATION
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;

SELECT DISTINCT PRODUCT_CATEGORY
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;

SELECT DISTINCT product_type
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;


---------------------------------------------

SELECT MIN(TRANSACTION_DATE) AS SHOP_OPENING_DATE
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;
-----------------------------------------------
SELECT MAX(TRANSACTION_DATE) AS LAST_OPERATING_DATE
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;

------------------------------------------------------
SELECT TRANSACTION_DATE,
       DAYNAME(TRANSACTION_DATE)AS DAY_NAME 
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;
-------------------------------------------------
SELECT TRANSACTION_DATE,
        DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
        MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME
FROM CASESTUDY.BRIGHT.COFFEE_SHOP;
-------------------------------------------------

SELECT TRANSACTION_DATE,
        DAYNAME(TRANSACTION_DATE)AS DAY_NAME,
        CASE
        WHEN DAY_NAME IN ('SUN','SAT')THEN 'WEEKEND' 
        ELSE 'WEEKDAY'
        END AS DAY_CLASSIFICATION,
        MONTHNAME(TRANSACTION_DATE)AS MONTH_NAME, 
       CASE
       WHEN TRANSACTION_TIME BETWEEN '06:00:00'AND '11:59:59'THEN' MORNING' 
       WHEN TRANSACTION_TIME BETWEEN '12:00:00'AND '16:59:59'THEN 'AFTERNOON'
       WHEN TRANSACTION_TIME >='17:00:00'THEN 'EVENING'
       END AS TIME_CLASSIFICATION,
       hour(TRANSACTION_TIME) AS HOUR_OF_DAY,
       STORE_LOCATION,
       PRODUCT_CATEGORY,
       PRODUCT_DETAIL,
       SUM(TRANSACTION_QTY*UNIT_PRICE)AS REVENUE,
       PRODUCT_TYPE
FROM CASESTUDY.BRIGHT.COFFEE_SHOP
GROUP BY ALL;


